<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0203_Suma_de_Matrices_y_Vectores_(broadcasting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [ ]:
#A = vector + matriz

In [ ]:
A = matriz.T + vector

In [ ]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [ ]:
C = matriz + 42

In [ ]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [ ]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


In [ ]:
#Tarea
vector_5 = np.array([1,1,1,1,1])
matriz_5 = np.array([
                      [1,1,1,1,1],
                      [1,1,1,1,1],
                      [1,1,1,1,1],
                      [1,1,1,1,1],
                      [1,1,1,1,1]
])

print(vector_5 + matriz_5)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
