<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0301_Producto_interno_entre_una_matriz_y_un_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [ ]:
A = matriz * vector

In [ ]:
B = matriz.dot(vector)

In [ ]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [ ]:
print(B)

[ 8 18 28]


In [ ]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [ ]:
D = np.array([[2],[2],[2]])

In [ ]:
print(D)

[[2]
 [2]
 [2]]


In [ ]:
# Tarea
A2 = vector * matriz
# B2 = vector.dot(matriz)
C2 = np.dot(vector, matriz)
print(A2)
print(B2)
print(C2)

ValueError: ignored