<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0303_Propiedades_del_producto_interno_Asociativa_Dist_Conmutativa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [ ]:
# Asociativa
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [ ]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [ ]:
#Distrbutiva
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [ ]:
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [ ]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [ ]:
F = B.dot(C)

In [ ]:
G = C.dot(B)

In [ ]:
print(F==G)

[[False False]
 [False False]]


In [ ]:
print(F)

[[15  7]
 [10  4]]


In [ ]:
print(G)

[[ 5 10]
 [ 8 14]]


In [ ]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [ ]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [ ]:
print(v1_tv2)

[[41]]


In [ ]:
print(v2_tv1)

[[41]]
