<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0304_Transposicion_de_un_producto_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [ ]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [ ]:
print(B)

[[1 3]
 [2 1]]


In [ ]:
AB_t = A.dot(B).T

In [ ]:
B_tA_t = B.T.dot(A.T)

In [ ]:
print(AB_t == B_tA_t)

[[ True  True  True]
 [ True  True  True]]


In [ ]:
print(AB_t)

[[ 8 19 37]
 [ 9 22 46]]
