<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0401_Matrices_identidad_inversa_singular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
identidad = np.eye(4)

In [ ]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
vector = np.array([[2],[3],[5],[7]])

In [ ]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [ ]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [ ]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

In [ ]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [ ]:
inversa_A = np.linalg.inv(A)

In [ ]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [ ]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
singular = np.array([[1,1],[1,1]])

In [ ]:
print(singular)

[[1 1]
 [1 1]]


In [ ]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix