<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0402_Aplicacion_de_la_inversa_de_una_matriz_para_resolver_un_sistema_de_ecuaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.set_printoptions(suppress=True)

In [ ]:
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [ ]:
b = np.array([[1],[1]])

In [ ]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [ ]:
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


In [ ]:
print(A.dot(x))

[[1.]
 [1.]]


In [ ]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]


In [ ]:
print(A.dot(sol_2))

[[3.]
 [7.]]
