<a href="https://colab.research.google.com/github/DavidSA06/Math-for-Data-Science/blob/main/0602_Tipos_de_Normas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vector = np.array([1,2,0,5,6,0])
#L_0 = Cantidad de elementos distintos de 0
print(np.linalg.norm(vector, ord=0))

4.0


In [ ]:
vector = np.array([1,-1,1,-1,1])
#L_1 = Suma de los valores absolutos
print(np.linalg.norm(vector, ord=1))

5.0


In [ ]:
vector = np.array([1,1])

In [ ]:
#L_2 = Distancia euclidiana sqrt(x_1^2+x_2^2)
print(np.linalg.norm(vector))
print(np.linalg.norm(vector, ord=2))

1.4142135623730951
1.4142135623730951


In [ ]:
vector = np.array([1,2,3,4,5,6])
print(vector)

[1 2 3 4 5 6]


In [ ]:
#L_2^2 = Distancia euclidiana al cuadrado (x_1^2+x_2^2)^2
print(np.linalg.norm(vector, ord=2)**2)

91.0


In [ ]:
#L_2^2 = Producto punto, escalar, interno
print(vector.T.dot(vector))

91


In [ ]:
#L_\infty = máximo absoluto de los componentes del vector
vector = np.array([1,2,3,-100])
print(np.linalg.norm(vector, ord=np.inf))

100.0


In [ ]:
mat1 = np.array([[7,-7,3],
                [1,1,0],
                [0,0,1]])

mat2 = np.array([[7,-5,3],
                [1,2,0],
                [4,0,1]])

mat3 = np.array([[7,-5],
                [1,2]])
v3 = np.array([[3],[3]])
print(mat1.dot(mat2))
print(mat2.dot(mat1))
print(3+mat3)
print(mat3+v3)
escalar = 3.1
mat1.shape

[[ 54 -49  24]
 [  8  -3   3]
 [  4   0   1]]
[[ 44 -54  24]
 [  9  -5   3]
 [ 28 -28  13]]
[[10 -2]
 [ 4  5]]
[[10 -2]
 [ 4  5]]


(3, 3)